### ISSUE TITLE
Doesn't run on Windows 10 64-bit

### ISSUE THREAD

**Issue by thebitstick** [skijump/windows-media-center-sdk#1]

**Comment by retrosight** [comment]
The Windows Media Center SDK was designed to run on Windows 7 Home Premium and Ultimate. It was never intended to run on later versions of Windows and I would not expect it to run.

**Comment by retrosight** [comment]
See https://github.com/skijump/windows-media-center-sdk/blob/primary/faq.md#version-compatibility
