### ISSUE TITLE
Release under an Open Source license

### ISSUE THREAD

**Issue by mikemaccana** [skijump/windows-media-center-sdk#3]
The current license (at https://github.com/skijump/windows-media-center-sdk/blob/primary/docs/source/Eula.txt) seems to be for a binary app and makes little sense for something on GitHub, as it forbids forks, multiple backups, etc.

This should be reviewed by someone at Microsoft and released officially.

**Comment by retrosight** [comment]
This repository is 100% about preserving history, similar to https://github.com/historicalsource. If you'd like to reach out to Microsoft to discuss: feel free to do so.

**Comment by retrosight** [comment]
The majority of the SDK was sample code which is freely redistributable under the original EULA.
